##XML格式文件
#logging.pattern.console="%d - %msg%n"
##logging.path=C:\\logs
#logging.file=C:\\logs\\sell.log
##logging.pattern.level=debug
#logging.pattern.level=vip.iotworld.main.LoggerTest:debug

#YML文件格式
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.173.128:3306/shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /wechat-sell
